### PR TITLE
Modify clustered scenario schema in cassandra doc 

### PR DESCRIPTION
**Pull request by shankarramshivram**
- Modify clustered scenario schema to include orgid 
- modify 'DC1' to 'dc1' in keyspace definition

### CODE REVIEW

**Comment by Dieterbe** [comment]
>

**Comment by shankarramshivram** [comment]
When i tried to start the cluster -- metrictank seems to require "dc1" instead of "DC1" as datacenter name..  It seems cassandra datacenter names are  case sensitive..

**Comment by woodsaj** [comment]
Metrictank will require the datacenter name you have configured Cassandra to use.  The default datacenter name is "DC1", so that is what the docs need to use.

**Comment by shankarramshivram** [comment]
@woodsaj -- reverted the dc name change.

**Comment by Dieterbe** [comment]
thanks @shankarramshivram !

**Pull request merged**
