### PR TITLE
update idxDelete unit test to fail if it takes too long

### PR DESCRIPTION
**Pull request by woodsaj**
- the main purpose of this is to ensure that deletes of nodes with
a large number of children dont take too long. So the unit test
has been updated to fail if the operation takes more then 10seconds.

### CODE REVIEW

**Comment by woodsaj** [comment]
unit tests are to validate correct behaviour. If this test fails , which it will if the change is the delete function is reverted, then it means something is broken.

Benchmarks dont prevent builds from completing.  But the build should definitely fail if this test fails.

**Comment by Dieterbe** [comment]
that's a road without an end. following the same reasoning we can start writing unit tests that we're able to ingest x points per second, that render requests can be responded to in x time, that we can add y items to the index per second and so on. there's tens of things like that that are the same as what you're doing, but it doesn't change the fact that unit tests are not a good way to keep tabs on performance characteristics. much more useful would be visualizing benchmark results over time. since a while now we already execute benchmarks in every build, but the next step we need is comparing the results over time and alerting in case of significant regressions in any benchmark.
what you're doing is also very binary.  it wouldn't detect if a delete used to take 2s but suddenly takes 8s.

**Comment by woodsaj** [comment]
you are completely missing the point.  We had a bug that caused an outage for a customer.  This unit test ensures that bug does not re-appear.

**Comment by Dieterbe** [comment]
that point is not lost on me. we can solve the same problem in a better way using go's benchmark feature.

**Pull request merged**
