### PR TITLE
add support for retrying cassandra queries

### PR DESCRIPTION
**Pull request by Dieterbe**

### CODE REVIEW

**Comment by Dieterbe** [comment]
note: have not been able to trigger retries in testing yet

**Comment by dgryski** [comment]
Use a tcp hazard proxy?

**Comment by woodsaj** [comment]
@dieter are using the "delay" scripts in the chaos dir of raintank-docker?

**Comment by Dieterbe** [comment]
Good ideas guys. I've been testing with https://github.com/raintank/raintank-docker/pull/85 (toxiproxy) which is a scriptable, userspace-only tcp hazard proxy. seems like a better path forward then our current chaos scripts which require root and are a bit hacky.

this needs some more work, but some observations at this point:

* even with toxicity 1.0 (100%) at 1000ms +- 500ms, it seems the behavior is for some reason on-off. periods of hazard followed by normal response times
* i've not been able to reproduce chunks of data not showing up on charts which load historical data from cassandra, even during periods of hazard with cassandra-retry 0 :? i'm probably doing something wrong. i will revisit tomorrow.

if anyone wants to play with it, just use that raintank-docker branch, follow the instructions in the last commit. easiest if you use the cassandra-instrumentation metrictank branch with cassandra-retry cherry-picked on top.  make sure to run setup_dev.sh so you have the right metrictank build.
then just import the dashboard.json into grafana so you get the better insights into errors.

**Comment by Dieterbe** [comment]
## with cassandra-retries 2 
MT https://snapshot.raintank.io/dashboard/snapshot/OQZcPL5EtEPbSHjLwJxrZ1CYu7bmAbpn
sys https://snapshot.raintank.io/dashboard/snapshot/7W9GT5vIAfHXcb4CYL5wCVKXIK54O0uZ
```
HEALTHY:
listed 1061 metrics
Requests      [total, rate]            36000, 300.01
Duration      [total, attack, wait]    1m59.998454263s, 1m59.996654523s, 1.79974ms
Latencies     [mean, 50, 95, 99, max]  1.590466ms, 1.508235ms, 2.015497ms, 4.086365ms, 58.474174ms
Bytes In      [total, mean]            533080666, 14807.80
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:36000
Error Set:
Added downstream latency toxic 'latency_downstream' on proxy 'cassandra'
TIMEOUTS:
listed 1061 metrics
Requests      [total, rate]            36000, 300.01
Duration      [total, attack, wait]    1m59.997972172s, 1m59.996654517s, 1.317655ms
Latencies     [mean, 50, 95, 99, max]  878.408377ms, 893.337045ms, 1.863478513s, 1.999308818s, 2.060674936s
Bytes In      [total, mean]            519625656, 14434.05
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:36000
Error Set:
```

**Comment by Dieterbe** [comment]
## cassandra-retries = 3
 
MT https://snapshot.raintank.io/dashboard/snapshot/Gi0i2MOX3m2Ce3oZ6VY8fNl7Uqp8k0BH 
sys https://snapshot.raintank.io/dashboard/snapshot/r19QmAohHF56mcjL25cnNuQ1LqV00pzR

```
HEALTHY:
listed 1061 metrics
Requests      [total, rate]            36000, 300.01
Duration      [total, attack, wait]    1m59.998292521s, 1m59.996654537s, 1.637984ms
Latencies     [mean, 50, 95, 99, max]  1.747552ms, 1.601386ms, 2.347313ms, 4.967945ms, 70.002806ms
Bytes In      [total, mean]            533175063, 14810.42
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:36000
Error Set:
Added downstream latency toxic 'latency_downstream' on proxy 'cassandra'
TIMEOUTS:
listed 1061 metrics
Requests      [total, rate]            36000, 300.01
Duration      [total, attack, wait]    2m1.858446546s, 1m59.996654542s, 1.861792004s
Latencies     [mean, 50, 95, 99, max]  879.956641ms, 892.415633ms, 1.88501702s, 2.001256366s, 2.137042004s
Bytes In      [total, mean]            521367743, 14482.44
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:36000
Error Set:
```
==> looks identical to retries 2 :?

**Comment by Dieterbe** [comment]
## cassandra-retries 1
MT https://snapshot.raintank.io/dashboard/snapshot/5WPWoVHXbqjm1vHHaBIxCAxSAa9RZWeW
sys https://snapshot.raintank.io/dashboard/snapshot/KURQeMotejSfXl5yr8gCioa5qtWU6gA5
```
HEALTHY:
listed 1020 metrics
Requests      [total, rate]            36000, 300.01
Duration      [total, attack, wait]    1m59.997333728s, 1m59.996654547s, 679.181µs
Latencies     [mean, 50, 95, 99, max]  1.699684ms, 1.584158ms, 2.084203ms, 4.074211ms, 63.633215ms
Bytes In      [total, mean]            551090461, 15308.07
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:36000
Error Set:
Added downstream latency toxic 'latency_downstream' on proxy 'cassandra'
TIMEOUTS:
listed 1020 metrics
Requests      [total, rate]            36000, 300.01
Duration      [total, attack, wait]    2m1.504835012s, 1m59.996654524s, 1.508180488s
Latencies     [mean, 50, 95, 99, max]  906.171505ms, 909.037219ms, 1.880825595s, 2.000969284s, 2.070541414s
Bytes In      [total, mean]            537311412, 14925.32
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:36000
Error Set:
```

**Comment by Dieterbe** [comment]
OK so the TLDR is we now have enough knowledge about the tradeoffs of using retries.
we should play a bit more with different host policies (in particular tokenaware) in combination with retry settings in our new QA setup. but this should be good to merge.

**Pull request merged**
