### PR TITLE
set default cassandra keyspace to "metrictank"

### LINKED ISSUE #438: fix default cassandra keyspaces
* for idx, all config files/docs say he default is `raintank`, but the code uses `metrics` as default (!)
* for cassandraStore, we use `raintank` by default`

I have not checked the cookbook

I think we should just use `metrictank` as default keyspace for both. (e.g. in code, in all configs, in the docs and in the cookbook)

thoughts @woodsaj @replay ?

### PR DESCRIPTION
**Pull request by woodsaj**
closes #438

### CODE REVIEW

**Comment by Dieterbe** [comment]
@woodsaj i pushed some commits to make the change in some other places that were forgotten.
pro-tip: use `find . -name 'metrictank*.ini'  | xargs grep keyspace` to find all occurences in all configs. there's the sample config, the standard docker/package config, and then a few of the docker environments have a custom config. I've gotten used to the above command to find all configs in the repo (though we may want to reorganize them a bit but that's a different topic)

one thing left I think: `mt-index-migrate` still uses `raintank`. it also uses the same keyspace flag for both old and new index.
I think this tool should be changed to have -old-keyspace and -new-keyspace flags, with raintank as default for the former (since that was the default in 0.6) and metrictank as default for the latter (which is the new default for 0.7), since the tool migrates a 0.6 to a 0.7 one.

**Comment by woodsaj** [comment]
> I think this tool should be changed to have -old-keyspace and -new-keyspace flags, with raintank as default 

I disagree, this is a version migration tool. It is expected to be run on a deployment before the MT instances are upgraded.  upgrading MT would not change the keyspace used by the MT instance (as that would result in the user losing access to all of their data) so it doesnt make sense to have this tool move the index to a different keyspace.


but i do agree that mt-idx-migrate should use the new default keyspace name to be consistent.

**Comment by Dieterbe** [comment]
> upgrading MT would not change the keyspace used by the MT instance

only if the user uses a configuration that overrides the default and sticks to that configuration.
note that apt and the like help with package upgrades by making the user review and/or merge in the new config matching the upgraded binary, which would have the new keyspace.
I guess it's common enough that people will stick to their old values and leave the keyspace, but I do think the defaults represent what we encourage, that's why they are in the default configs, so our index migration can also encourage switching to the new default while they're at it.

> as that would result in the user losing access to all of their data

i don't understand this. why would this be the case? if you migrate to a new index in a different keyspace (the new default in this case, but that doesn't matter), then when you upgrade your MT you would either use the default (in which case it would use the correct keyspace, not losing access), or configure it whatever is the correct value.

**Comment by woodsaj** [comment]
>i don't understand this. why would this be the case?

This tool only changes the index table, it doesnt touch the metrics table.  Running with the metrics in one keyspace and the index in another is a bad idea.

**Comment by Dieterbe** [comment]
so what do you suggest: give `mt-index-migrate` a new default keyspace of `metrictank` since that's what we recommend now, but knowing that almost everyone will have to override it with `raintank`? then we should just leave it at `raintank` I think.

**Comment by woodsaj** [comment]
Then lets just leave it as "raintank" and merge this.

**Pull request merged**
