### PR TITLE
Minor improvements to documentation of docker setup

### PR DESCRIPTION
**Pull request by replay**
I went step by step through the Docker documentation. The only problem I've had was that at first I used `apt-get install` to install `docker-compose`, which in Ubuntu `16.04` gave me version `1.5.2`. 

The `docker-compose.yml` file requires a version of `>=1.7`. Assuming that other people might make the same mistake I added a special note pointing out that the returned error means the version of `docker-compose` needs to be updated.

### CODE REVIEW

**Comment by Dieterbe** [comment]
looks good, thanks!

**Comment by Dieterbe** [comment]
btw @replay was it hard to get 1.7 in your ubuntu? how did you do it?

**Comment by replay** [comment]
@Dieterbe No it wasn't hard at all once I realized that my problem was the version of `docker-compose`. But it took me a while to realize that because the error wasn't very self explanatory.
 
I just did what this page describes: https://docs.docker.com/compose/install/

So:
```
# curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
```

Then it worked

**Comment by Dieterbe** [comment]
k neat. i was wondering if we're too strict expecting people to get >= 1.7 but seems like it's not so bad when the user is willing to bypass their package manager. long term would be nice if we can just use the stuff packaged in the distros themselves though, so we should be more considerate adopting new compose features in the future.

**Comment by replay** [comment]
Yeah, I guess as long as it's as easy as just downloading a script and running it it should be fine to ask the users to do that. Let's hope Ubuntu updates to 1.7 soon and then we should probably just stick to that version on our work stations, to not accidentally use newer features without realizing that backwards compatibility is broken. 
Writing some test that runs on Circle CI and builds the docker containers might also work, but I don't know enough about Circle CI to be certain about whether they allow us to create containers there. I'd guess at least building (without starting) should be possible.

**Comment by replay** [comment]
@Dieterbe If you agree that it would make sense to setup a Circle CI test to test the build I could create an Issue and then I'd try doing that. That way we could effectively be sure that the steps described in the docs always work the way they're described. What do you think?

**Comment by Dieterbe** [comment]
funny you should ask, this is one of the things on my todo list. sure, feel free to go for it.
just so we're clear, what we want to happen in circleCi is
* build the latest binary, build the latest docker file (this already happens)
* docker-compose up the bring up the stack
* wait until MT listens on its listenaddr
* do some testing. perhaps write some metrics to the carbon input port, and validate that we can query for the data and that it looks good? we could potentially even use https://github.com/raintank/fakemetrics to send a fixed input rate (say 1kHz) and then also query MT's `stats.$environment.metrictank.$host.carbon.metrics_received` and make sure it matches
* shut down stack again using docker-compose, and only push packages/dockerfile/... if the testing was ok

**Comment by replay** [comment]
Awesome, so a full end-to-end test. Yeah, if Circle CI allows us to start the docker images inside their test boxes then I agree that's the way to go. 

Once that works we could almost base the install docs on the test ;)

**Comment by replay** [comment]
Circle CI has beta support for running docker containers in their test boxes, so I'll try that: https://circleci.com/docs/docker/

**Comment by Dieterbe** [comment]
@replay according to https://docs.docker.com/compose/compose-file/#/version-2 docker compose >=1.6 should work (well technically they say `Compose 1.6.0+` but I think that's what that means). do you remember why we need 1.7 ?

**Comment by OOM-Killer** [comment]
You're totally right. I think I followed some Github thread where they talked about `docker-compose` not being backwards compatible where a guy mentioned he made it work after updating to `1.7` and then i forgot to back check with the docs. Good catch!

**Comment by OOM-Killer** [comment]
created the PR #351

**Comment by replay** [comment]
You're totally right. I think I followed some Github thread where they talked about docker-compose not being backwards compatible where a guy mentioned he made it work after updating to 1.7 and then i forgot to back check with the docs. Good catch!

**Comment by Dieterbe** [comment]
#351

**Pull request merged**
